INSERT INTO productos (titulo_productos, descripcion, cantidad, categoria) VALUES
('Laptop Lenovo ThinkPad', 'Laptop empresarial con procesador Intel i5, 16GB RAM, 512GB SSD', 10, 'Electrónica'),
('Silla ergonómica', 'Silla para oficina con soporte lumbar ajustable', 25, 'Muebles'),
('Teclado mecánico', 'Teclado gamer retroiluminado RGB', 50, 'Accesorios'),
('Café Colombiano', 'Café de origen 100% colombiano, bolsa de 500g', 100, 'Alimentos'),
('Camiseta deportiva', 'Camiseta dry-fit transpirable, talla M', 40, 'Ropa'),
('Mouse inalámbrico', 'Mouse óptico con conectividad Bluetooth y USB', 60, 'Accesorios'),
('Monitor 24 pulgadas', 'Monitor Full HD con panel IPS', 15, 'Electrónica'),
('Zapatos deportivos', 'Zapatos running con amortiguación avanzada', 30, 'Ropa'),
('Auriculares inalámbricos', 'Auriculares Bluetooth con cancelación de ruido', 35, 'Electrónica'),
('Mesa de madera', 'Mesa rectangular de madera de roble', 12, 'Muebles'),
('Agua mineral 1.5L', 'Botella de agua mineral natural', 200, 'Alimentos'),
('Bolso de cuero', 'Bolso de cuero sintético unisex', 18, 'Accesorios'),
('Impresora láser', 'Impresora monocromática con conexión WiFi', 8, 'Electrónica'),
('Escritorio gamer', 'Escritorio con soporte para monitor y luces LED', 6, 'Muebles'),
('Chocolate artesanal', 'Tableta de chocolate 70% cacao colombiano', 120, 'Alimentos');
