# Etapa 1: Compilación con Maven y JDK 17
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# Copiar pom, src y proto
COPY pom.xml .
COPY src ./src
COPY src/main/proto ./src/main/proto

# Compilar y empaquetar
RUN mvn clean package -DskipTests

# Etapa 2: Imagen ligera para ejecutar el JAR
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copiar el JAR compilado desde la etapa de build
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

# Ejecutar la aplicación
CMD ["java", "-jar", "app.jar"]
